[package]
name = "solar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
json = "0.12"
zip = "0.6.4"
md5 = "0.7.0"